#syntax=docker/dockerfile:1

FROM ubuntu:20.04

#EXPOSE 3309

WORKDIR /opt/app
COPY flask_app/ .

RUN apt-get update
RUN apt-get install -y libmysqlclient-dev
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN pip3 install -r requirements.txt

CMD ["python3", "app.py"]
